"""foto projeto

Revision ID: 6ce8f516154a
Revises: b9cb70f6c8ac
Create Date: 2020-10-23 07:59:50.372955-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce8f516154a'
down_revision = 'b9cb70f6c8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_projeto', sa.Column('foto_capa', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_projeto', 'foto_capa')
    # ### end Alembic commands ###
